learning: 

  step_size: 0.01
  batch_size: 1500
  num_iters: 5000
  decay_rate: 0.99

network: 

    layer_depths: [32, 64, 128, 256, 512]
    layer_kernel_sizes: [[3,3], [3,3], [3, 3], [3,3], [3,3]]

display: 

    refresh_rate: 10

